import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Menu } from '@/components/Menu'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='min-h-screen flex flex-col font-serif'>
        <Header />
        <Menu />
        <div className="flex flex-1 pt-4">
          <div className="w-1/5">left sidebar</div>
          <div className="flex-1 px-4">{children}</div>
          <div className="w-1/5">right sidebar</div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
